### POST Access User Account
POST http://127.0.0.1:3000/accounts/access HTTP/1.1
Content-Type: application/json

{
    "username": "efefewfwe",
    "userPassword": "2"
}

### POST Create User Account
POST http://127.0.0.1:3000/accounts/create HTTP/1.1
Content-Type: application/json

{
    "username": "efefewfwe",
    "userPassword": "1"
}

