### POST Access User Account (no cookie)
POST http://127.0.0.1:3000/user/account/access HTTP/1.1
Content-Type: application/json

{
    "username": "jorgenson",
    "userPassword": "1"
}

### POST Access User Account (cookie)
POST http://127.0.0.1:3000/user/account/access HTTP/1.1
Content-Type: application/json

{
    "username": "jorgenson",
    "userPassword": "1",
    "cookie": "sessionId=0KmsyBpv-UbNCXMFFAcG6QU_qrsuewOb.%2FeGtYBJdKopXRcDRx4xncLVZc0PG2U%2F6nwf7ObA6UrQ; Path=/user; Expires=Sat, 21 Jun 2025 19:44:39 GMT; HttpOnly; SameSite=Strict"
}

### POST Create User Account
POST http://127.0.0.1:3000/user/account/create HTTP/1.1
Content-Type: application/json

{
    "username": "noway",
    "userPassword": "1"
}

### POST Fetch Save Slots
POST http://127.0.0.1:3000/user/save-slots/access HTTP/1.1
Content-Type: application/json

{
    "cookie": "sessionId=0KmsyBpv-UbNCXMFFAcG6QU_qrsuewOb.%2FeGtYBJdKopXRcDRx4xncLVZc0PG2U%2F6nwf7ObA6UrQ; Path=/user; Expires=Sat, 21 Jun 2025 19:55:18 GMT; HttpOnly; SameSite=Strict"
}

### POST Update Save Slots
POST http://127.0.0.1:3000/user/save-slots/update HTTP/1.1
Content-Type: application/json

{
    "1": {
        "factory": {
            "inserter": {
                "irptu": "1000"
            }
        }
    },
    "2": {
        "stuff": {
            "otherstuff": {
                "eeee": "1321321312"
            }
        }
    },
    "3": {
        "yooooooow": {
            "wdqwd": {
                "ewdqdwee": "123123231"
            }
        }
    },
    "cookie": "sessionId=0KmsyBpv-UbNCXMFFAcG6QU_qrsuewOb.%2FeGtYBJdKopXRcDRx4xncLVZc0PG2U%2F6nwf7ObA6UrQ; Path=/user; Expires=Sat, 21 Jun 2025 19:55:18 GMT; HttpOnly; SameSite=Strict"
}


